### ISSUE TITLE
运行JEKYDE,出现问题

### ISSUE THREAD

**Issue by luckypoem** [zohooo/jekyde#1]
HI.如何解决下面的问题？

as3:~/jekyde-blog# ls
as3:~/jekyde-blog# jekyde
Initializing default content folder...
Initializing default template folder...

/usr/local/lib/node_modules/jekyde/builder/converter/swig.js:5
swig.init({
     ^
TypeError: Object #<Object> has no method 'init'
    at Object.<anonymous> (/usr/local/lib/node_modules/jekyde/builder/converter/swig.js:5:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/jekyde/builder/plugin/website/category.js:4:12)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
as3:~/jekyde-blog#

**Comment by zohooo** [comment]
这是由于 Jekyde 所依赖的 Swig 的版本变化引起的。Jekyde 0.3.5 已经解决这个问题，你可以重新安装。
